export interface ThemePreset {
  id: string;
  label: string;
  light: Record<string, string>;
  dark: Record<string, string>;
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'amber',
    label: 'Amber Warm',
    light: {
      '--background': '#faf7f2',
      '--foreground': '#1a1815',
      '--card': '#ffffff',
      '--card-foreground': '#1a1815',
      '--primary': '#b0751a',
      '--primary-foreground': '#faf7f2',
      '--secondary': '#f0ebe0',
      '--secondary-foreground': '#1a1815',
      '--muted': '#f0ebe0',
      '--muted-foreground': '#7a7065',
      '--accent': '#f0ebe0',
      '--accent-foreground': '#1a1815',
      '--destructive': '#c46b6b',
      '--border': '#e6e0d8',
      '--ring': '#b0751a',
      '--info': '#6d5d9e',
      '--success': '#3d7a5a',
      '--warning': '#c8a040',
    },
    dark: {
      '--background': '#17120d',
      '--foreground': '#e8dcc8',
      '--card': '#1f1914',
      '--card-foreground': '#e8dcc8',
      '--primary': '#c8842c',
      '--primary-foreground': '#17120d',
      '--secondary': '#241e18',
      '--secondary-foreground': '#e8dcc8',
      '--muted': '#241e18',
      '--muted-foreground': '#8a7b6b',
      '--accent': '#241e18',
      '--accent-foreground': '#e8dcc8',
      '--destructive': '#c46b6b',
      '--border': 'rgba(232,220,200,0.08)',
      '--ring': '#c8842c',
      '--info': '#a898d8',
      '--success': '#5d8a5e',
      '--warning': '#c8a040',
    },
  },
  {
    id: 'blue',
    label: 'Blue Classic',
    light: {
      '--background': '#f8fafc',
      '--foreground': '#0f172a',
      '--card': '#ffffff',
      '--card-foreground': '#0f172a',
      '--primary': '#2563eb',
      '--primary-foreground': '#ffffff',
      '--secondary': '#f1f5f9',
      '--secondary-foreground': '#0f172a',
      '--muted': '#f1f5f9',
      '--muted-foreground': '#64748b',
      '--accent': '#f1f5f9',
      '--accent-foreground': '#0f172a',
      '--destructive': '#ef4444',
      '--border': '#e2e8f0',
      '--ring': '#2563eb',
      '--info': '#8b5cf6',
      '--success': '#22c55e',
      '--warning': '#f59e0b',
    },
    dark: {
      '--background': '#0f172a',
      '--foreground': '#f1f5f9',
      '--card': '#1e293b',
      '--card-foreground': '#f1f5f9',
      '--primary': '#3b82f6',
      '--primary-foreground': '#0f172a',
      '--secondary': '#1e293b',
      '--secondary-foreground': '#f1f5f9',
      '--muted': '#1e293b',
      '--muted-foreground': '#94a3b8',
      '--accent': '#1e293b',
      '--accent-foreground': '#f1f5f9',
      '--destructive': '#ef4444',
      '--border': 'rgba(255,255,255,0.1)',
      '--ring': '#3b82f6',
      '--info': '#a78bfa',
      '--success': '#4ade80',
      '--warning': '#fbbf24',
    },
  },
  {
    id: 'green',
    label: 'Green Forest',
    light: {
      '--background': '#f6faf7',
      '--foreground': '#0f1a12',
      '--card': '#ffffff',
      '--card-foreground': '#0f1a12',
      '--primary': '#16a34a',
      '--primary-foreground': '#ffffff',
      '--secondary': '#ecf7ef',
      '--secondary-foreground': '#0f1a12',
      '--muted': '#ecf7ef',
      '--muted-foreground': '#5a7a62',
      '--accent': '#ecf7ef',
      '--accent-foreground': '#0f1a12',
      '--destructive': '#e04444',
      '--border': '#d0e0d4',
      '--ring': '#16a34a',
      '--info': '#7c3aed',
      '--success': '#16a34a',
      '--warning': '#d97706',
    },
    dark: {
      '--background': '#0a0f0c',
      '--foreground': '#dcf0e2',
      '--card': '#101a13',
      '--card-foreground': '#dcf0e2',
      '--primary': '#22c55e',
      '--primary-foreground': '#0a0f0c',
      '--secondary': '#101a13',
      '--secondary-foreground': '#dcf0e2',
      '--muted': '#101a13',
      '--muted-foreground': '#6b8a72',
      '--accent': '#101a13',
      '--accent-foreground': '#dcf0e2',
      '--destructive': '#f87171',
      '--border': 'rgba(220,240,226,0.08)',
      '--ring': '#22c55e',
      '--info': '#a78bfa',
      '--success': '#4ade80',
      '--warning': '#fbbf24',
    },
  },
  {
    id: 'purple',
    label: 'Purple Night',
    light: {
      '--background': '#faf8fc',
      '--foreground': '#1a0f2a',
      '--card': '#ffffff',
      '--card-foreground': '#1a0f2a',
      '--primary': '#7c3aed',
      '--primary-foreground': '#ffffff',
      '--secondary': '#f3eefc',
      '--secondary-foreground': '#1a0f2a',
      '--muted': '#f3eefc',
      '--muted-foreground': '#6b5a8a',
      '--accent': '#f3eefc',
      '--accent-foreground': '#1a0f2a',
      '--destructive': '#e0446b',
      '--border': '#e0d8ec',
      '--ring': '#7c3aed',
      '--info': '#7c3aed',
      '--success': '#16a34a',
      '--warning': '#d97706',
    },
    dark: {
      '--background': '#0f0a18',
      '--foreground': '#e8dcf8',
      '--card': '#1a1028',
      '--card-foreground': '#e8dcf8',
      '--primary': '#a855f7',
      '--primary-foreground': '#0f0a18',
      '--secondary': '#1a1028',
      '--secondary-foreground': '#e8dcf8',
      '--muted': '#1a1028',
      '--muted-foreground': '#8a6baa',
      '--accent': '#1a1028',
      '--accent-foreground': '#e8dcf8',
      '--destructive': '#fb7185',
      '--border': 'rgba(232,220,248,0.08)',
      '--ring': '#a855f7',
      '--info': '#c4b5fd',
      '--success': '#4ade80',
      '--warning': '#fbbf24',
    },
  },
  {
    id: 'rose',
    label: 'Rose Dawn',
    light: {
      '--background': '#fcf8f8',
      '--foreground': '#2a0f15',
      '--card': '#ffffff',
      '--card-foreground': '#2a0f15',
      '--primary': '#e11d48',
      '--primary-foreground': '#ffffff',
      '--secondary': '#fceef2',
      '--secondary-foreground': '#2a0f15',
      '--muted': '#fceef2',
      '--muted-foreground': '#8a5a65',
      '--accent': '#fceef2',
      '--accent-foreground': '#2a0f15',
      '--destructive': '#e11d48',
      '--border': '#ecd8de',
      '--ring': '#e11d48',
      '--info': '#7c3aed',
      '--success': '#16a34a',
      '--warning': '#d97706',
    },
    dark: {
      '--background': '#180a0f',
      '--foreground': '#f8dce4',
      '--card': '#281018',
      '--card-foreground': '#f8dce4',
      '--primary': '#f43f5e',
      '--primary-foreground': '#180a0f',
      '--secondary': '#281018',
      '--secondary-foreground': '#f8dce4',
      '--muted': '#281018',
      '--muted-foreground': '#aa6b7a',
      '--accent': '#281018',
      '--accent-foreground': '#f8dce4',
      '--destructive': '#fb7185',
      '--border': 'rgba(248,220,228,0.08)',
      '--ring': '#f43f5e',
      '--info': '#c4b5fd',
      '--success': '#4ade80',
      '--warning': '#fbbf24',
    },
  },
];

export function getPreset(id: string): ThemePreset | undefined {
  return THEME_PRESETS.find(p => p.id === id);
}
